feat: deprecate python 3.7
replicate/cog pull request #1550
Opened 2024-02-25 21:25 UTC by dkhokhlov

- do not allow python 3.7 in models
- added test:  test_integration/test_build.py::test_python_37_depricated

Ref: issue #1431

2024-02-25 21:35 UTC, technillogue commented on pyproject.toml
> +requires-python = ">=3.8"
this we can't do yet

2024-02-25 21:36 UTC, technillogue requested changes
otherwise looks solid

2024-02-25 21:36 UTC, technillogue commented on python/cog/types.py
> +                self._path.unlink(missing_ok=missing_ok)
this is a strange piece of code but also can't actually be dropped yet

2024-02-26 03:55 UTC, dkhokhlov commented
@technillogue 
It's interesting to note that Python 3.12 runs tests slower. I had to increase the deadline from 1000 to 1500 in the CI profile only.

2024-02-26 17:22 UTC, technillogue approved these changes

2024-02-26 17:40 UTC, merged